services:
  dsfs:
    build: .
    image: twtom/discordfs-sftp:latest
    ports:
      - "8022:8022"
    volumes:
      - ./.conf/webhooks.txt:/app/.conf/webhooks.txt
      - ./.conf/host_key:/app/.conf/host_key
      - ./.conf/bot_token:/app/.conf/bot_token
  mongodb:
    image: "mongo:7.0.5-rc0-jammy"
    container_name: "mongodb-dsfs"
    expose:
      - "27017"
    