services:
  dsfs:
    build: .
    image: twtom/discordfs-sftp:latest
    ports:
      - "8022:8022"
    volumes:
      - ./webhooks.txt:/app/webhooks.txt
  mongodb:
    image: "mongo:7.0.5-rc0-jammy"
    container_name: "mongodb-dsfs"
    expose:
      - "27017"
    